### PR TITLE
Refactor by using creation time

### PR DESCRIPTION
**Pull request by j8r**
Huge refactor of the library, inspired by another implementation I have done on another project. I thought first to create my own library, but since this one already exists, I said to myself "why not trying to improve it".

This is a **breaking-change**, indeed.

### Convenience

There are several advantages of storing the creation time instead of the expiration time:
- we can change the period of validity easily
- we know exactly when they key was created

There are also methods that have changed or removed to better fit the actual Crystal convention (no symbol, `?` when nillable).

I removed the `update` method, since for me I consider using this as elegant, with a more minimal API:
```cr
unless value = cache.read? "key"
  value = cache.write("key", 1)
end
```

### Performance

A Memory Cache is supposed to be as fast as possible, but actually it can be much faster.

A thing that has changed is the removal of the expiration check each time a key is fetched.
This has been removed to considerably speed the fetch of the key, without having to make a system call to know the date, and compare against the key one.

If one still wants to check the expiration date every-time, because it is a strong requirement to exactly match the expiration date; a new method `#delete_if_older` has been added.

If one wants different expiration dates, (s)he can use different stores which will be garbage-collected differently, there lots of other ways to achieve this.

We could have both the creation time and the expiration time stored, but I think it is not necessary to complicate the library.

### Specs

Each test has been made independent from each other; the `CACHE` variable has been removed.

The `spec_helper` file has been removed, because not much was inside anymore.

---

Thanks you!

### CODE REVIEW

**Comment by j8r** [comment]
For questions I have, I'm not sure about the `#fetch` and `#read_entry` (return a Tuple?) APIs - suggestions welcome!

**Comment by oprypin** [comment]
This basically drops the functionality of time-limited cache, which is the whole point.

It also makes it impossible to make this library thread-safe.

If you want something that fits your different use case, please make a different library.

**Comment by j8r** [comment]
I don't see the difference in thread-safety in this implementation and the other, this is about the same in read/write.

**Comment by j8r** [comment]
I think both expiration time and creation can be stored, and have both features.

**Comment by oprypin** [comment]
Usage before:

```crystal
cache.fetch(id, expires_in: 55.minutes) do
  new(id)
end.last
```

Usage after:

```crystal
cache.delete_if_older(55.minutes)
unless value = cache.read?(id)
  value = cache.write(id, new(id))
end 
```

Why?

**Comment by j8r** [comment]
It is non intuitive to modify a value. In the stdlib, every `fetch` use like `Hash#fetch` are only read operations.

**Comment by kostya** [comment]
Thansks. But yes, i agree, read and fetch should check expire every time. I expect it work as memcached. Return tuple because one my usecase need to know what i readed.

**Comment by j8r** [comment]
yep, we can have a `fetch` that checks the expiration, agreed. But, we agree that having a method called `fetch` doing a write operation is not ideal?

**Comment by j8r** [comment]
also, why return tuple on fetch? If the block is executed, the result is not cached. If not, it is.

**Comment by kostya** [comment]
ok, i think ok to remove tuples, and i can set bool flag inside block. About update, i agree with @oprypin, it more like atomic operation, which possible to make thread safe in future.

**Comment by straight-shoota** [comment]
That tuple return type was unexpected to me, too. It's totally unnecessary because you know there was no cache hit when the block is executed.

**Comment by straight-shoota** [comment]
Many smaller changes from this PR definitely look like great additions (independent specs, examples, API docs).

**Comment by j8r** [comment]
Sure, closing this.

**Pull request closed without merging**
