### PR TITLE
Don't unnecessarily capture blocks. This limits control flow

### PR DESCRIPTION
**Pull request by oprypin**
and probably is also slower.

### CODE REVIEW

**Comment by kostya** [comment]
thanks

**Comment by kostya** [comment]
btw, spec failed:
```
  1) MemoryCache(K, V) fetch with control flow
     Failure/Error: cache.fetch(k) do

       Expected: {:fetch, 5}
            got: 5

     # spec/memory_cache_spec.cr:171
```

**Comment by oprypin** [comment]
Sorry about that, I don't know how I missed that.

So this spec is how I wish it would work, but apparently it's not possible to actually have that behavior. Instead, `break` acts pretty much the same as raising an exception; the value gets forgotten. So we're just lucky that the API returns a tuple of two items normally, otherwise people wouldn't even realize that their cache silently doesn't work if they use `break`.

Don't know if it's good to even fix the spec, probably better to just delete it.

**Comment by straight-shoota** [comment]
@oprypin you should probably use `next` instead of `break`, then the spec succeeds.

**Pull request merged**
